# Generated by Django 4.1.1 on 2023-02-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='03-05-1999', upload_to='pics'),
            preserve_default=False,
        ),
    ]
